# Generated by Django 4.0.1 on 2022-01-14 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_alter_advertisement_options_advertisement_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
