# Generated by Django 4.0 on 2021-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Показание', 'verbose_name_plural': 'Показания'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
